language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

install:
  - composer install --no-progress --profile

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - php bin/ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
